/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';
import PaytabsSdk from 'react-native-paytabs-sdk';

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Button title={'Open Paytabs'} onPress={() => {
          PaytabsSdk.openPaytab({
            merchant_email: 'hello@gotostandout.com',
            secret_key: 'FysJ43VBWamYqp8Rpq7zzHgB43TAz3beBEYGHThE4DCu3Kmtbu2LbimgmgQVj2aUG8Bo1S25wEAzpX2Br5mDoJTKZJGjLQesYPQ0',
            language: 'en',
            transaction_title: 'Test Paytabs library',
            order_id: '123456',
            amount: '99.99',
            currency_code: 'BHD',
            phone_number: '009733',
            customer_email: 'customer-email@example.com',
            address_billing: 'Flat 1,Building 123, Road 2345',
            city_billing: 'Manama',
            state_billing: 'Manama',
            country_billing: 'BHR',
            postal_code_billing: '00973',
            address_shipping: 'Flat 1,Building 123, Road 2345',
            city_shipping: 'Manama',
            state_shipping: 'Manama',
            country_shipping: 'BHR',
            postal_code_shipping: '00973',
            pay_button_color: '#2474bc'
          }, (data) => {
            console.log(data);
          })
        }} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
